In [199]:
import pandas as pd

In [213]:
### Function that takes in proposed_gen csv for a year, returns the proposed generators of certain technology
### or energy source
### TO DO: Make more general for any CSV of this format(feed in file name)

def makeGenOfTypeDF(year, tech_code="PV", energy_code = "SUN"):
    proposed_gen_df = pd.read_csv("../Data for Tax Equity Project/eia_data/eia860" + str(year) + "/proposed_gen_" + str(year) + ".csv")
    proposed_gen_df.columns = map(str.lower, proposed_gen_df.columns)
    pmList = ['prime_mover', 'prime mover', 'primemover']
    enList = ['energy_source_1']
    for pm in pmList:
        if pm in proposed_gen_df.columns:
            tech_df = proposed_gen_df[proposed_gen_df[pm]==tech_code]
    for en in enList:
        if en in proposed_gen_df.columns:
            en_df = proposed_gen_df[proposed_gen_df[en]==energy_code]
            tech_df = tech_df.combine_first(en_df)
    return(tech_df)

In [218]:
for x in range(2008,2014):
    print(str(x) + ": " + str(makeGenOfTypeDF(x).shape[0]))

2008: 48
2009: 188
2010: 357
2011: 325
2012: 328
2013: 590

In [217]:
makeGenOfTypeDF(2009)

,utility_id,utility_name,plant_code,plant_name,state,county,generator_id,prime_mover,status,nameplate,...,pulverized_coal,fluidized_bed,subcritical,supercritical,ultrasupercritical,carboncapture,startup_source_1,startup_source_2,startup_source_3,startup_source_4
15,803.0,Arizona Public Service Co,56228.0,Prescott Airport,AZ,Yavapai,PV2,PV,P,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,803.0,Arizona Public Service Co,57324.0,Luke Solar,AZ,Maricopa,PV1,PV,P,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,4922.0,Dayton Power & Light Co,2854.0,Yankee Street,OH,Montgomery,YS1,PV,U,1.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,5416.0,"Duke Energy Carolinas, LLC",57334.0,DE Solar 10240 Old Dowd Rd,NC,Mecklenburg,PV01,PV,P,1.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,5416.0,"Duke Energy Carolinas, LLC",57335.0,DE Solar 657 Brigham Rd,NC,Guilford,PV01,PV,U,1.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
909,56673.0,White Oak Solar Energy LLC,57337.0,Dover Sun Park,DE,Kent,1,PV,T,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
910,56674.0,NRG NM Suntower LLC,57338.0,New Mexico Solar,NM,Dona Ana,1,PV,L,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
911,56675.0,NRG Gaskell LLC,57339.0,Gaskell Solar,CA,Kern,1,PV,P,141.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
912,56676.0,Solargen Energy Inc,57340.0,Panoche Valley Solar Farm,CA,San Benito,1,PV,L,385.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
913,56681.0,Kent County Levy Court Dept of Pub Work,57330.0,Plant 1,DE,Kent,1,PV,U,1.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN