## I'm going to remove 1603 and Doe Loan guarantee program projects and see what happens.  I think there will be a more pronounced spike in what remains

In [102]:
import pandas as pd

In [141]:
# list of operating projects in 2018
gen = pd.read_csv('/Users/rachelanderson/Dropbox (Princeton)/Data for Tax Equity Project/eia_data/eia8602018/merged_new.csv')
gen = gen[~gen['utility_name'].isna()]
gen['nameplate_cap'] = pd.to_numeric(gen['nameplate_capacity_mw'].astype(str).str.replace(',',''))

/Users/rachelanderson/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (17,40,44,78) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [142]:
#list of funded capacity 
grant_recips = pd.read_excel('../../../Data for Tax Equity Project/treasury_data/grant_awards.xlsx',header=1)

In [302]:
#create variables for receiving 1603 loan grant or 1705 

#DoE 1705 utility-scale recipients
searchfor = ['Agua Caliente', 'California Valley Solar', 
             'Desert Sun','Mesquite Solar 1', 'AV Solar',
            'Cogentrix', 'Crescent Dune','Ivanpah',
            'Genesis Solar Energy Project',
            'Mojave Solar Project',
            'Solana', ]

gen['1603_grant'] = gen['plant_name'].isin(grant_recips['Business Name']) | gen['utility_name'].isin(grant_recips['Business Name'])
gen['1705_grant'] = gen['plant_name'].str.contains('|'.join(searchfor))

In [306]:
gen[gen['plant_name'].str.contains('Solana')][['utility_name','plant_state','plant_name','nameplate_cap','technology']]

,utility_name,plant_state,plant_name,nameplate_cap,technology
15342,Arizona Solar One LLC,AZ,Solana Generating Station,140.0,Solar Thermal with Energy Storage
15343,Arizona Solar One LLC,AZ,Solana Generating Station,140.0,Solar Thermal with Energy Storage

In [280]:
arra_names = gen[gen['plant_name'].isin(grant_recips['Business Name']) | gen['utility_name'].isin(grant_recips['Business Name'])]['plant_name'].values
doe_names = gen[gen['plant_name'].str.contains('|'.join(searchfor))]['plant_name'].values
loan_dict = dict.fromkeys(arra_names, '1603 grant')
loan_dict.update(dict.fromkeys(doe_names, '1705 program'))

In [291]:
gen['grant_program'] = gen['plant_name'].map(loan_dict)
gen['grant_program'] = gen['grant_program'].fillna("none")

In [292]:
gen.to_csv('/Users/rachelanderson/Dropbox (Princeton)/Data for Tax Equity Project/eia_data/eia8602018/merged_new.csv')

In [138]:
# finds exact matches from generators to loan grants

gen_grants = gen[gen['Utility Name'].isin(grant_recips['Business Name'])]
gen_grants[['Utility Name','nameplate_cap', 'Plant Name', 'Technology']].sort_values(by=['nameplate_cap'],ascending=False)
gen_grants[gen_grants['Technology'].str.contains("Solar")]

,Unnamed: 0,Utility ID,Utility Name,Plant Code,Plant Name,State,County,Generator ID,Technology,Prime Mover,...,Planned New Nameplate Capacity (MW),Planned Repower Month,Planned Repower Year,Other Planned Modifications?,Other Modifications Month,Other Modifications Year,Multiple Fuels?,Cofire Fuels?,Switch Between Oil and Natural Gas?,nameplate_cap
15342,15342,56023,Arizona Solar One LLC,56812.0,Solana Generating Station,AZ,Maricopa,GEN 1,Solar Thermal with Energy Storage,CP,...,,,,N,,,N,N,N,140.0
15343,15343,56023,Arizona Solar One LLC,56812.0,Solana Generating Station,AZ,Maricopa,GEN2,Solar Thermal with Energy Storage,CP,...,,,,N,,,N,N,N,140.0
15523,15523,57044,"Constellation Solar New Jersey, LLC",56900.0,Atlantic City Convention Center,NJ,Atlantic,1,Solar Photovoltaic,PV,...,,,,NaN,,,NaN,NaN,NaN,0.5
15524,15524,57044,"Constellation Solar New Jersey, LLC",56900.0,Atlantic City Convention Center,NJ,Atlantic,2,Solar Photovoltaic,PV,...,,,,NaN,,,NaN,NaN,NaN,0.5
15525,15525,57044,"Constellation Solar New Jersey, LLC",56900.0,Atlantic City Convention Center,NJ,Atlantic,3,Solar Photovoltaic,PV,...,,,,NaN,,,NaN,NaN,NaN,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21861,21861,5416,"Duke Energy Carolinas, LLC",62304.0,Woodleaf Solar Facility,NC,Rowan,PV1,Solar Photovoltaic,PV,...,,,,NaN,,,NaN,NaN,NaN,6.0
21867,21867,61012,AES Distributed Energy,62324.0,Dynamic - Walpole,MA,Norfolk,WAL01,Solar Photovoltaic,PV,...,,,,NaN,,,NaN,NaN,NaN,2.0
21934,21934,61969,Altorfer Inc.,62451.0,Rantoul Solar,IL,Champaign,RANTL,Solar Photovoltaic,PV,...,,,,NaN,,,NaN,NaN,NaN,1.0
22080,22080,62655,RC Energy AA LLC,62756.0,RC Energy AA LLC Solar Facility,NM,Bernalillo,AA001,Solar Photovoltaic,PV,...,,,,NaN,,,NaN,NaN,NaN,1.0
22093,22093,62727,Nextsun Energy Littleton LLC,62842.0,Nextsun Energy Littleton,MA,Middlesex,1-003,Solar Photovoltaic,PV,...,,,,NaN,,,NaN,NaN,NaN,5.0

In [135]:
# finds matches from loan grant recips to utilities 

grant_recips[grant_recips['Business Name'].isin(gen['Utility Name'])]

,Business Name,State,Technology,Funded,Award Date
55,Arizona Solar One LLC,AZ,Solar Electricity,513753359.0,2014-03-04 00:00:00
158,"Gilbert Solar Facility I, LLC",AZ,Solar Electricity,2505195.0,2012-07-10 00:00:00
268,RE Ajo 1 LLC,AZ,Solar Electricity,6605741.0,2012-12-31 00:00:00
269,RE Bagdad Solar 1 LLC,AZ,Solar Electricity,22909331.0,2012-12-31 00:00:00
346,"Tech Park Solar, LLC",AZ,Solar Electricity,4464795.0,2014-03-26 00:00:00
...,...,...,...,...,...
9780,"Sagebrush Power Partners, LLC",WA,Wind,53420192.0,2011-01-28 00:00:00
9792,GL Dairy Biogas LLC,WI,"Biomass (open loop, livestock)",2231830.0,2014-05-29 00:00:00
9993,"FCPC Renewable Generation, LLC",WI,Trash Facility,5178221.0,2014-09-10 00:00:00
9996,Richland Center Renewable Energy LLC,WI,Trash Facility,7346948.0,2013-05-10 00:00:00
10002,Hawks Nest Hydro LLC,WV,Hydropower (incremental),6429574.0,2014-05-30 00:00:00

In [30]:
desertSun = gen[gen['Utility Name'].str.contains("NextEra Energy Desert Sunlight")]

In [16]:
desertSun['Nameplate Capacity (MW)'].sum()

563.4000000000001

In [31]:
desertSun[['Plant Name', 'Utility Name', 'Generator ID', 'Nameplate Capacity (MW)','Operating Month', 'Operating Year']]

,Plant Name,Utility Name,Generator ID,Nameplate Capacity (MW),Operating Month,Operating Year
17177,"Desert Sunlight 300, LLC","NextEra Energy Desert Sunlight 300, LLC",DSL1,40.3,11.0,2013.0
17178,"Desert Sunlight 300, LLC","NextEra Energy Desert Sunlight 300, LLC",DSL10,30.2,11.0,2013.0
17179,"Desert Sunlight 300, LLC","NextEra Energy Desert Sunlight 300, LLC",DSL11,20.2,11.0,2013.0
17180,"Desert Sunlight 300, LLC","NextEra Energy Desert Sunlight 300, LLC",DSL2,40.3,11.0,2013.0
17181,"Desert Sunlight 300, LLC","NextEra Energy Desert Sunlight 300, LLC",DSL3,40.3,11.0,2013.0
17182,"Desert Sunlight 300, LLC","NextEra Energy Desert Sunlight 300, LLC",DSL4,30.2,11.0,2013.0
17183,"Desert Sunlight 300, LLC","NextEra Energy Desert Sunlight 300, LLC",DSL5,25.2,6.0,2014.0
17184,"Desert Sunlight 300, LLC","NextEra Energy Desert Sunlight 300, LLC",DSL6,25.2,8.0,2014.0
17185,"Desert Sunlight 300, LLC","NextEra Energy Desert Sunlight 300, LLC",DSL7,20.2,8.0,2014.0
17186,"Desert Sunlight 300, LLC","NextEra Energy Desert Sunlight 300, LLC",DSL8,18.9,10.0,2014.0
17187,"Desert Sunlight 300, LLC","NextEra Energy Desert Sunlight 300, LLC",DSL9,22.7,10.0,2014.0
18005,"Desert Sunlight 250, LLC","NextEra Energy Desert Sunlight 250, LLC",DSL12,39.1,12.0,2013.0
18006,"Desert Sunlight 250, LLC","NextEra Energy Desert Sunlight 250, LLC",DSL13,39.1,1.0,2014.0
18007,"Desert Sunlight 250, LLC","NextEra Energy Desert Sunlight 250, LLC",DSL14,26.5,4.0,2014.0
18008,"Desert Sunlight 250, LLC","NextEra Energy Desert Sunlight 250, LLC",DSL15,13.9,6.0,2014.0
18009,"Desert Sunlight 250, LLC","NextEra Energy Desert Sunlight 250, LLC",DSL16,22.7,11.0,2013.0
18010,"Desert Sunlight 250, LLC","NextEra Energy Desert Sunlight 250, LLC",DSL17,29,11.0,2013.0
18011,"Desert Sunlight 250, LLC","NextEra Energy Desert Sunlight 250, LLC",DSL18,29,6.0,2014.0
18012,"Desert Sunlight 250, LLC","NextEra Energy Desert Sunlight 250, LLC",DSL19,25.2,10.0,2014.0
18013,"Desert Sunlight 250, LLC","NextEra Energy Desert Sunlight 250, LLC",DSL20,25.2,11.0,2013.0

347.7